import Head from 'next/head';
import React from 'react';
import Hero from '../components/home-page/hero';
import { getAllItems, getFeaturedItems } from '../public/lib/items-util';
import About from '../components/home-page/about';

export default function Home(props) {
  return (
    <fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* eslint-disable-next-line react/prop-types,react/destructuring-assignment */}
      <Hero heroItems={props.heroItems} />
      <About />
    </fragment>
  );
}

export function getStaticProps() {
  const heroItems = getAllItems('heros');
  const posts = getAllItems('posts');
  const projects = getAllItems('projects');
  const services = getAllItems('services');
  const pricingItems = getAllItems('pricing');
  const testimonialItems = getAllItems('testimonial');
  const brandItems = getAllItems('brands');
  const LatestProject = getFeaturedItems(projects);
  const FeaturedPost = getFeaturedItems(posts);

  return {
    props: {
      heroItems,
      projects: LatestProject,
      posts: FeaturedPost,
      services,
      pricingItems,
      testimonialItems,
      brandItems,
    },
  };
}
